from main import * 

el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(4)")
el1.click()
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Settings")
el2.click()
el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Account settings for u/jimmyy")
el3.click()
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Manage notifications")
el4.click()
# el5 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(5)")
# el5.click()
# el5.click()
el6 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(0)")
el6.click()
el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(1)")
el7.click()
el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(2)")
el8.click()
el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(3)")
el9.click()
el10 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(4)")
el10.click()
el11 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(5)")
el11.click()
el12 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(6)")
el12.click()
el13 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(7)")
el13.click()
el14 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(8)")
el14.click()
el14.click()
el13.click()
el12.click()
el11.click()
el10.click()
el9.click()
el8.click()
el7.click()
el6.click()
# el15 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(7)")
# el15.click()
# el16 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(6)")
# el16.click()
# el17 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(5)")
# el17.click()
# el18 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(4)")
# el18.click()
# el19 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(3)")
# el19.click()
# el20 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(2)")
# el20.click()
# el21 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(1)")
# el21.click()
# el22 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(0)")
# el22.click()
el23 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="r/Testing Community")
el23.click()
el24 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el24.click()
el25 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el25.click()
el26 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Activity")
el26.click()
el27 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el27.click()
el28 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Posts with Upvotes")
el28.click()
el29 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(1)")
el29.click()
el29.click()
el30 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(0)")
el30.click()
el30.click()
el31 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el31.click()
el32 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el32.click()
el33 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Posts with Comments")
el33.click()
el34 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el34.click()
el35 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el35.click()
el36 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el36.click()
el37 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el37.click()
el38 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el38.click()
el39 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el39.click()
