import sys
sys.path.append('E:\Spring2024\SW\Phase3\mobile_tests\MobileTesting\Phase_4')
from main import *



el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(4)")
el1.click()
time.sleep(0.5)
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Settings")
el2.click()
time.sleep(0.5)
el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Account settings for u/jimmyy")
el3.click()
time.sleep(0.5)
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Manage notifications")
el4.click()
time.sleep(0.5)
el6 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(0)")
el6.click()
time.sleep(0.5)
el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(1)")
el7.click()
time.sleep(0.5)
el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(2)")
el8.click()
time.sleep(0.5)
el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(3)")
el9.click()
time.sleep(0.5)
el10 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(4)")
el10.click()
time.sleep(0.5)
el11 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(5)")
el11.click()
time.sleep(0.5)
el12 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(6)")
el12.click()
time.sleep(0.5)
el13 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(7)")
el13.click()
time.sleep(0.5)
el14 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(8)")
el14.click()
time.sleep(0.5)
el14.click()
time.sleep(0.5)
el13.click()
time.sleep(0.5)
el12.click()
time.sleep(0.5)
el11.click()
time.sleep(0.5)
el10.click()
time.sleep(0.5)
el9.click()
time.sleep(0.5)
el8.click()
time.sleep(0.5)
el7.click()
time.sleep(0.5)
el6.click()
time.sleep(0.5)
el23 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="r/Testing Community")
el23.click()
time.sleep(0.5)
el24 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el24.click()
time.sleep(0.5)
el25 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el25.click()
time.sleep(0.5)
el26 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Activity")
el26.click()
time.sleep(0.5)
el27 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el27.click()
time.sleep(0.5)
el28 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Posts with Upvotes")
el28.click()
time.sleep(0.5)
el29 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(1)")
el29.click()
time.sleep(0.5)
el29.click()
time.sleep(0.5)
el30 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Switch\").instance(0)")
el30.click()
time.sleep(0.5)
el30.click()
time.sleep(0.5)
el31 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el31.click()
time.sleep(0.5)
el32 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el32.click()
time.sleep(0.5)
el33 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Posts with Comments")
el33.click()
time.sleep(0.5)
el34 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el34.click()
time.sleep(0.5)
el35 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el35.click()
time.sleep(0.5)
el36 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el36.click()
time.sleep(0.5)
el37 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el37.click()
time.sleep(0.5)
el38 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el38.click()
time.sleep(0.5)
el39 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
el39.click()