import sys
sys.path.append('E:\Spring2024\SW\Phase3\mobile_tests\MobileTesting\Phase_4')
from main import *


el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"u/Super Mario\").instance(0)")
el1.click()
sleep(0.5)
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Unfollow")
el2.click()
sleep(0.5)
el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Follow")
el3.click()
sleep(0.5)
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Comments\nTab 2 of 3")
el4.click()
sleep(0.5)
el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="About\nTab 3 of 3")
el5.click()
sleep(0.5)
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Posts\nTab 1 of 3")
el6.click()
sleep(0.5)
el7 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="mario_emad_")
el7.click()
sleep(0.5)
el8 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Close tab")
el8.click()
sleep(0.5)
el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(28)")
el9.click()
sleep(0.5)
