from main import *
community_name="jimmy's new community"
def createCommunity():
    el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(4)")
    el1.click()
    sleep(2)
    el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Create a community")
    el2.click()
    sleep(2)
    el3 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
    el3.click()
    sleep(2)
    el3.send_keys(community_name)
    sleep(2)
    el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Public")
    el4.click()
    sleep(2)
    el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Public")
    el5.click()
    sleep(2)
    el6 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
    el6.click()
    sleep(2)
    el7 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Create Community")
    el7.click()
    sleep(2)
    el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(3)")
    el8.click()
    sleep(2)
    el9 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Back")
    el9.click()
    sleep(2)
    # el10 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Communities\nTab 2 of 5")
    # el10.click()
    # sleep(2)
    el11 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Home\nTab 1 of 5")
    el11.click()
createCommunity()