from main import *

def scenario1():
    el7 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Already a redditor? Log in")
    el7.click()
    el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.EditText\").instance(0)")
    # el8.send_keys("jimmyy")
    # el8.click()
    el8.send_keys("jimmyy")
    el8.click()
    el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.FrameLayout\").instance(0)")
    el9.click()
    el10 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.FrameLayout\").instance(0)")
    el10.click()
    el11 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.EditText\").instance(1)")
    el11.click()
    el11.send_keys("pass1234")
    el12 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Conitnue")
    el12.click()
    el12.send_keys("pass1234")
    el12.click()
    el13 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Create\nTab 3 of 5")
    el13.click()
    el14 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.EditText\").instance(0)")
    el14.click()
    el14.send_keys("my post")
    el15 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.EditText\").instance(1)")
    el15.click()
    el15.send_keys("the content I'm adding")
    el16 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Next")
    el16.click()
    el17 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
    el17.click()
    el17.send_keys("football")
    el18 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
    el18.click()
    el19 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(0)")
    el19.click()
    el20 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(4)")
    el20.click()
    el21 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Create a community")
    el21.click()
    el22 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
    el22.click()
    el22.send_keys("testingSquad")
    el23 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Create Community")
    el23.click()

scenario1()