from main import *

# Actually, this function tests and 'stars' the 'Following' list, not the 'Communities'.

def staracommunity():
    el1 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Open navigation menu")
    el1.click()
    sleep(1)
    el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Communities")
    el2.click()
    sleep(1)
    el3 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
    el3.click()
    sleep(1)
    el3.click()
    sleep(1)
    el3.click()
    sleep(1)
    el3.click()
    sleep(1)
    el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Following")
    el4.click()
    el5 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(1)")
    el5.click()
    sleep(1)
    el6 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(3)")
    el6.click()
    sleep(1)
    el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(1)")
    el7.click()
    sleep(1)
    el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(2)")
    el8.click()
    el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(3)")
    el9.click()
    el11 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Home\nTab 1 of 5")
    el11.click()
    # el11.click()
staracommunity()