from main import *
#this likely upvotes the first existing post and comments on it the forthcoming comment
comment_content="newest comment 17/4/2013"
def upvoteDownvoteComment():
    el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(14)")
    el1.click()
    el1.click()
    el2 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(15)")
    el2.click()
    sleep(1)
    el2.click()
    el3 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(14)")
    el3.click()
    sleep(1)
    el4 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(15)")
    sleep(1)
    el4.click()
    el5 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(16)")
    el5.click()
    sleep(1)
    el6 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
    el6.click()
    el6.send_keys(comment_content)
    el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(12)")
    el7.click()
    el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(0)")
    el8.click()
    # el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(13)")
    # el9.click()
    # el10 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Hide")
    # el10.click()
    
upvoteDownvoteComment()