import sys
sys.path.append('E:\Spring2024\SW\Phase3\mobile_tests\MobileTesting\Phase_4')
from main import *


el21 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"r/Flutter Community\").instance(0)")
el21.click()
assert_element(el21, "r/Flutter Community not found")
el26 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(2)")
el26.click()
assert_element(el26, "Button not found")
el27 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Learn more about this community")
el27.click()
assert_element(el27, "Learn more about this community not found")
el28 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(2)")
el28.click()
assert_element(el28, "Button not found")
el29 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(3)")
el29.click()
assert_element(el29, "Button not found")
el30 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(0)")
el30.click()
assert_element(el30, "Button not found")
el31 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Message Moderators")
el31.click()
assert_element(el31, "Message Moderators not found")
el32 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Mute r/Flutter Community")
el32.click()
assert_element(el32, "Mute r/Flutter Community not found")
el33 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Leave")
el33.click()
assert_element(el33, "Leave not found")
el34 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Leave Community")
el34.click()
assert_element(el34, "Leave Community not found")
