import sys
sys.path.append('E:\Spring2024\SW\Phase3\mobile_tests\MobileTesting\Phase_4')
from main import *
newContent="Get in losers, we're editing this post to see the testing function."
el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(4)")
el1.click()
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="My profile")
el2.click()
el3 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(22)")
el3.click()
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Edit post")
el4.click()
el5 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el5.click()
# el5.send_keys("Get in losers, we're editing this post to see the testing function.")
el5.clear()
el5.send_keys(newContent)
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Save")
el6.click()
el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(0)")
el7.click()
el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(4)")
el8.click()
el9 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="My profile")
el9.click()
